name: Build & deploy
on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #   - main
  
jobs:
  build_and_deploy:
    name: Build and deploy production
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: npm
    - run: npm install
    - run: npm run build
    - name: rsync
      run: |
        echo "${{ secrets.YOZO_OOO_SSH_PRIVATE_KEY }}" > deploy_key
        chmod 600 ./deploy_key
        rsync \
          --archive \
          --delete \
          --rsh='ssh -i ./deploy_key -o StrictHostKeyChecking=no -o LogLevel=quiet' \
          dist/ ${{ secrets.YOZO_OOO_REMOTE }}:/var/www/yozo.ooo
