name: Build & deploy
on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #   - main
  
jobs:
  build_and_deploy:
    name: Build and deploy production
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: npm
    - run: npm install
    - run: npm run build
    - name: run rsync using ssh
      run: |
        # run rsync using ssh
        mkdir -p ~/.ssh/
        echo "${{ secrets.YOZO_OOO_SECRET_KEY }}" > deploy_key
        chmod 600 ./deploy_key
        echo "${{ secrets.YOZO_OOO_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        rsync \
          --archive \
          --verbose \
          --rsh='ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          dist/ ${{ secrets.YOZO_OOO_REMOTE }}:/var/www/yozo.ooo
